Resources:
    AWS: Add Debug Configuration
    WinterSGAudit:
        Type: AWS::Serverless::Function
        Properties:
            Handler: lambda_function.lambda_handler
            Runtime: python 3.14
            CodeUri: .